inputFile: /home/douglas/Documents/projetos/java/hbase-bulkload/massa.csv
quorum: "127.0.0.1"
port: "2181"
tableName: players_data
rowKey: Id:Group:Country:Jersey
rowValues  :
  - qualifier   : main:id
    value       : Id
  - qualifier   : main:name
    value       : Player
  - qualifier   : main:age
    value       : Age
  - qualifier   : main:position
    value       : Position
  - qualifier   : main:club
    value       : Club
  - qualifier   : main:iscaptain
    value       : Captain
